### ISSUE TITLE
transport: Handle unsuccessful connections gracefully

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#496]
### What happened?

For example, when the transport is not able to connect over ssh, we currently see a panic at https://github.com/gittuf/gittuf/blob/v0.5.2/internal/git-remote-gittuf/ssh.go#L303 during a push instead of terminating gracefully.

### Relevant log output

```Shell
ssh: connect to host REDACTED port 22: No route to host
panic: runtime error: slice bounds out of range [4:0]

goroutine 1 [running]:
main.handleSSH({0xc00031fee8?, 0x1?}, {0x7ff7b96663f7?, 0x36?})
        /Users/REDACTED/go/pkg/mod/github.com/gittuf/gittuf@v0.5.2/internal/git-remote-gittuf/ssh.go:303 +0x3030
main.run()
        /Users/REDACTED/go/pkg/mod/github.com/gittuf/gittuf@v0.5.2/internal/git-remote-gittuf/main.go:147 +0x348
main.main()
        /Users/REDACTED/go/pkg/mod/github.com/gittuf/gittuf@v0.5.2/internal/git-remote-gittuf/main.go:244 +0xde
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by R4R3D1FF** [comment]
I would like to work on this issue, can it be assigned to me?

**Comment by R4R3D1FF** [comment]
Oh nevermind, I realised this is already fixed in main.

**Comment by patzielinski** [comment]
Closing since this hasn't popped up in a while, if this issue appears again, let's file a new issue.
